### ISSUE TITLE
Segfaults with python3

### ISSUE THREAD

**Issue by doublex** [spotify/sparkey-python#3]
````
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    writer = sparkey.LogWriter(logfile)
  File "/usr/local/lib/python3.6/dist-packages/sparkey/__init__.py", line 161, in __init__
    compression_block_size)
  File "/usr/local/lib/python3.6/dist-packages/sparkey/__init__.py", line 56, in wrapper
    code = fn(*a, **kw)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
Segmentation fault
````

Python 3.6.3

**Comment by spkrka** [comment]
Can you provide more information on how this is triggerered? A small code sample that triggers it would be sufficient.

**Comment by doublex** [comment]
python2 works
OS: Ubuntu-17.10

Installed by:
````
python3 setup.py build
python3 setup.py install
````

Testcase: (both files don't exist)
````
import sparkey

logfile = '/tmp/test.log'
hashfile = '/tmp/test.hash'

writer = sparkey.LogWriter(logfile)
for i in range(0, 10):
    writer.put('key%d' % i, 'value%d' % i)
writer.close()

sparkey.writehash(hashfile, logfile)
````

**Comment by spkrka** [comment]
Thanks! I will try to investigate if I get time, but I can't promise any quick work on this.

**Comment by doublex** [comment]
Thanks!
This database would be incredibly helpful.
Kyotocabinet is slow inserting billions of records.
Maybe it is something very simple related to
    `def _ctypes_wrapper(func, ret, *args):`

**Comment by doublex** [comment]
Fixed:
a) In python3 you have to pass bytes (b'test') not a string ('test')
b) This patch allow to use bytes:
````
*** __init__.py.old     2018-04-12 10:47:35.957865872 +0200
--- __init__.py 2018-04-12 10:47:39.830103308 +0200
*************** class LogWriter(object):
*** 200,209 ****
  
          """
          self._assert_open()
-         if type(key) != str:
-             raise SparkeyException("key must be a string")
-         if type(value) != str:
-             raise SparkeyException("value must be a string")
          _logwriter_put(self._log, len(key), key, len(value), value)
  
      def __delitem__(self, key):
--- 200,205 ----
*************** class LogWriter(object):
*** 217,224 ****
  
          """
          self._assert_open()
-         if type(key) != str:
-             raise SparkeyException("key must be a string")
          _logwriter_delete(self._log, len(key), key)
  
  
--- 213,218 ----
````

**Comment by spkrka** [comment]
I don't think that's quite enough - the migration to python3 requires more.

Can you please take a look at this PR and see if it works? If so, I can merge it:
https://github.com/spotify/sparkey-python/pull/4

**Comment by spkrka** [comment]
Thanks for finding the problem with bytes/strings!

**Comment by doublex** [comment]
Tested (only python3)
Excellent! Thanks a lot!

**Comment by doublex** [comment]
Great database by the way. 
`tokyo cabinet` is so slow (~30 billions records)

**Comment by spkrka** [comment]
Fixed with #4

**Comment by spkrka** [comment]
That's a lot of data - you might want to consider using sparkey-java for the hash writing if that's a single hash index. An index of 30 billion would be `30 * (10^9) * 16 * (1.3 bytes) = 624 GB` which likely doesnt fit in RAM.  Sparkey-java recently solved that problem in this PR: https://github.com/spotify/sparkey-java/pull/33

**Comment by doublex** [comment]
Thanks a lot for pointing out.
It would be enough to run the `sparkey.writehash()` in Java?

**Comment by spkrka** [comment]
Yes, that's the only memory intensive operation in sparkey (appending to log files is cheap)

**Comment by doublex** [comment]
Thanks a lot!
Best wishes from Vienna
